name: ForceSpanwpoint
version: 1.1
main: io.github.bigcookie233.forcespawnpoint.ForceSpawnpoint
author: Bigcookie233
commands:
  forcespawnpoint:
    description: ForceSpawnpoint
    usage: /forcespawnpoint reload
    permission: op